services:
  frontend-dev:
    container_name: nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles: ["dev"]

  frontend-prod:
    container_name: nextjs-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles: ["prod"]
