import type { Metadata } from "next";
import "./globals.css";
import { Kanit, Nunito, Rubik } from 'next/font/google'

export const metadata: Metadata = {
  title: "Dev Next Js",
  description: "Generated by create next app",
};

const kanit = Kanit({
  weight: ["600"],
  style: ["normal", "italic"],
  subsets: ["latin"]
})

const nunito = Nunito({
  weight: ["600"],
  style: ["normal", "italic"],
  subsets: ["latin"]
})

const rubik = Rubik({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"]
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.className}>
      <body className="bg-white text-gray-900 font-sans">
        <div className="flex flex-col min-h-screen">
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
